-- Catalogo de orgaos (RN) para vinculo de perfis e tela de login.
-- Repetir a migracao nao duplica: conflito em (name) e ignorado.

insert into public.organizations (name) values
  ('ARSEP'),
  ('AGN'),
  ('ASSECOM'),
  ('CAERN'),
  ('CBM'),
  ('CEASA/RN'),
  ('CEHAB'),
  ('CONTROL'),
  ('DATANORTE'),
  ('DEI'),
  ('DER/RN'),
  ('DETRAN/RN'),
  ('DPE'),
  ('EMATER'),
  ('EMGERN'),
  ('EMPARN'),
  ('EMPROTUR'),
  ('FAPERN'),
  ('FJA'),
  ('FUNDASE'),
  ('GAC'),
  ('GVG'),
  ('IDEMA'),
  ('IDIARN'),
  ('IFESP'),
  ('IGARN'),
  ('IPEM'),
  ('IPERN'),
  ('ITEP/RN'),
  ('JUCERN'),
  ('PCRN'),
  ('PGE'),
  ('PMRN'),
  ('POTIGÁS'),
  ('SAPE'),
  ('SEAD'),
  ('SEAP'),
  ('SECULT'),
  ('SEDEC'),
  ('SEDRAF'),
  ('SEEC'),
  ('SEMARH'),
  ('SEMJIDH'),
  ('SEPLAN'),
  ('SESAP'),
  ('SESED'),
  ('SEFAZ'),
  ('SETHAS'),
  ('SETUR'),
  ('SIN'),
  ('UERN')
on conflict (name) do nothing;
